name: 'sonar'
on:
  push: 
    branches:
      - master
  # See https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request_target for security implications.
  pull_request_target:
      types: [opened, synchronize, reopened]
  pull_request:
      types: [opened, synchronize, reopened]

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2       
      - name: Set up JDK    
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Install dependencies
        run: npm install

      - name: SonarCloud Scan
        if: matrix.node-version == 14 
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=${{ steps.info.outputs.repo_owner }}
            -Dsonar.projectKey=${{ steps.info.outputs.repo_name }}
