name: 'sonar'
on:
  push: 
    branches:
      - master
  # See https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request_target for security implications.
  pull_request_target:
      types: [opened, synchronize, reopened]
  pull_request:
      types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
