on:
  pull_request:
      types: [opened, synchronize, reopened]

name: SonarCloud Scan

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
